// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdvInfoData.proto

package com.racerssquad.besthack2023.DTO.proto;

public interface AdvInfoDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.racerssquad.besthack2023.DTO.proto.AdvInfoData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Флаг указывающий на полное обновление данных или инкрементальное
   * </pre>
   *
   * <code>bool fullOrIncrement = 1;</code>
   * @return The fullOrIncrement.
   */
  boolean getFullOrIncrement();

  /**
   * <pre>
   * Записи со значениями полей
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.DataRow rows = 2;</code>
   */
  java.util.List<com.racerssquad.besthack2023.DTO.proto.DataRow> 
      getRowsList();
  /**
   * <pre>
   * Записи со значениями полей
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.DataRow rows = 2;</code>
   */
  com.racerssquad.besthack2023.DTO.proto.DataRow getRows(int index);
  /**
   * <pre>
   * Записи со значениями полей
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.DataRow rows = 2;</code>
   */
  int getRowsCount();
  /**
   * <pre>
   * Записи со значениями полей
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.DataRow rows = 2;</code>
   */
  java.util.List<? extends com.racerssquad.besthack2023.DTO.proto.DataRowOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <pre>
   * Записи со значениями полей
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.DataRow rows = 2;</code>
   */
  com.racerssquad.besthack2023.DTO.proto.DataRowOrBuilder getRowsOrBuilder(
      int index);
}
