// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdvInfoFieldRef.proto

package com.racerssquad.besthack2023.DTO.proto;

public final class AdvInfoFieldRefProto {
  private AdvInfoFieldRefProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_racerssquad_besthack2023_DTO_proto_AdvInfoFieldRef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_racerssquad_besthack2023_DTO_proto_AdvInfoFieldRef_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025AdvInfoFieldRef.proto\022&com.racerssquad" +
      ".besthack2023.DTO.proto\032\022MessageEnums.pr" +
      "oto\"\206\001\n\017AdvInfoFieldRef\022\r\n\005alias\030\001 \001(\t\022\024" +
      "\n\007caption\030\002 \001(\tH\000\210\001\001\022B\n\010dataType\030\003 \001(\01620" +
      ".com.racerssquad.besthack2023.DTO.proto." +
      "DataTypeB\n\n\010_captionB\032B\024AdvInfoFieldRefP" +
      "rotoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.getDescriptor(),
        });
    internal_static_com_racerssquad_besthack2023_DTO_proto_AdvInfoFieldRef_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_racerssquad_besthack2023_DTO_proto_AdvInfoFieldRef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_racerssquad_besthack2023_DTO_proto_AdvInfoFieldRef_descriptor,
        new java.lang.String[] { "Alias", "Caption", "DataType", "Caption", });
    com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
