// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataRow.proto

package com.racerssquad.besthack2023.DTO.proto;

public interface DataRowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.racerssquad.besthack2023.DTO.proto.DataRow)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Идентификатор записи
   * </pre>
   *
   * <code>string rowIdent = 1;</code>
   * @return The rowIdent.
   */
  java.lang.String getRowIdent();
  /**
   * <pre>
   * Идентификатор записи
   * </pre>
   *
   * <code>string rowIdent = 1;</code>
   * @return The bytes for rowIdent.
   */
  com.google.protobuf.ByteString
      getRowIdentBytes();

  /**
   * <pre>
   * Инкрементальное удаление записи (Удаление записи при инкрементальной передаче данных)
   * </pre>
   *
   * <code>bool incrementDelete = 2;</code>
   * @return The incrementDelete.
   */
  boolean getIncrementDelete();

  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.ValueRef values = 3;</code>
   */
  java.util.List<com.racerssquad.besthack2023.DTO.proto.ValueRef> 
      getValuesList();
  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.ValueRef values = 3;</code>
   */
  com.racerssquad.besthack2023.DTO.proto.ValueRef getValues(int index);
  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.ValueRef values = 3;</code>
   */
  int getValuesCount();
  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.ValueRef values = 3;</code>
   */
  java.util.List<? extends com.racerssquad.besthack2023.DTO.proto.ValueRefOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.ValueRef values = 3;</code>
   */
  com.racerssquad.besthack2023.DTO.proto.ValueRefOrBuilder getValuesOrBuilder(
      int index);
}
