// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package com.racerssquad.besthack2023.DTO.proto;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.racerssquad.besthack2023.DTO.proto.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Статус
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <pre>
   * Статус
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.Status status = 1;</code>
   * @return The status.
   */
  com.racerssquad.besthack2023.DTO.proto.Status getStatus();
  /**
   * <pre>
   * Статус
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.Status status = 1;</code>
   */
  com.racerssquad.besthack2023.DTO.proto.StatusOrBuilder getStatusOrBuilder();
}
