// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package com.racerssquad.besthack2023.DTO.proto;

public final class EventProto {
  private EventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_racerssquad_besthack2023_DTO_proto_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_racerssquad_besthack2023_DTO_proto_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Event.proto\022&com.racerssquad.besthack2" +
      "023.DTO.proto\032\014Status.proto\"G\n\005Event\022>\n\006" +
      "status\030\001 \001(\0132..com.racerssquad.besthack2" +
      "023.DTO.proto.StatusB\020B\nEventProtoH\001P\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.racerssquad.besthack2023.DTO.proto.StatusProto.getDescriptor(),
        });
    internal_static_com_racerssquad_besthack2023_DTO_proto_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_racerssquad_besthack2023_DTO_proto_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_racerssquad_besthack2023_DTO_proto_Event_descriptor,
        new java.lang.String[] { "Status", });
    com.racerssquad.besthack2023.DTO.proto.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
