// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Parameter.proto

package com.racerssquad.besthack2023.DTO.proto;

public final class ParameterProto {
  private ParameterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_racerssquad_besthack2023_DTO_proto_Parameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_racerssquad_besthack2023_DTO_proto_Parameter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Parameter.proto\022&com.racerssquad.besth" +
      "ack2023.DTO.proto\032\016ValueRef.proto\"\250\001\n\tPa" +
      "rameter\022\r\n\005alias\030\001 \001(\t\022\024\n\007caption\030\002 \001(\tH" +
      "\000\210\001\001\022\021\n\004hint\030\003 \001(\tH\001\210\001\001\022D\n\005value\030\004 \001(\01320" +
      ".com.racerssquad.besthack2023.DTO.proto." +
      "ValueRefH\002\210\001\001B\n\n\010_captionB\007\n\005_hintB\010\n\006_v" +
      "alueB\024B\016ParameterProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.racerssquad.besthack2023.DTO.proto.ValueRefProto.getDescriptor(),
        });
    internal_static_com_racerssquad_besthack2023_DTO_proto_Parameter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_racerssquad_besthack2023_DTO_proto_Parameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_racerssquad_besthack2023_DTO_proto_Parameter_descriptor,
        new java.lang.String[] { "Alias", "Caption", "Hint", "Value", "Caption", "Hint", "Value", });
    com.racerssquad.besthack2023.DTO.proto.ValueRefProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
