// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package com.racerssquad.besthack2023.DTO.proto;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.racerssquad.besthack2023.DTO.proto.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
   * @return The enum numeric value on the wire for command.
   */
  int getCommandValue();
  /**
   * <pre>
   * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
   * @return The command.
   */
  com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType getCommand();

  /**
   * <pre>
   * Тип собственной команды сервиса для исполнения.
   * </pre>
   *
   * <code>optional .com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec = 2;</code>
   * @return Whether the commandForExec field is set.
   */
  boolean hasCommandForExec();
  /**
   * <pre>
   * Тип собственной команды сервиса для исполнения.
   * </pre>
   *
   * <code>optional .com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec = 2;</code>
   * @return The commandForExec.
   */
  com.racerssquad.besthack2023.DTO.proto.OwnCommand getCommandForExec();
  /**
   * <pre>
   * Тип собственной команды сервиса для исполнения.
   * </pre>
   *
   * <code>optional .com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec = 2;</code>
   */
  com.racerssquad.besthack2023.DTO.proto.OwnCommandOrBuilder getCommandForExecOrBuilder();

  /**
   * <pre>
   * Список собственных команд сервиса
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
   */
  java.util.List<com.racerssquad.besthack2023.DTO.proto.OwnCommand> 
      getSupportedCommandsList();
  /**
   * <pre>
   * Список собственных команд сервиса
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
   */
  com.racerssquad.besthack2023.DTO.proto.OwnCommand getSupportedCommands(int index);
  /**
   * <pre>
   * Список собственных команд сервиса
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
   */
  int getSupportedCommandsCount();
  /**
   * <pre>
   * Список собственных команд сервиса
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
   */
  java.util.List<? extends com.racerssquad.besthack2023.DTO.proto.OwnCommandOrBuilder> 
      getSupportedCommandsOrBuilderList();
  /**
   * <pre>
   * Список собственных команд сервиса
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
   */
  com.racerssquad.besthack2023.DTO.proto.OwnCommandOrBuilder getSupportedCommandsOrBuilder(
      int index);
}
