// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Status.proto

package com.racerssquad.besthack2023.DTO.proto;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.racerssquad.besthack2023.DTO.proto.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Тип статуса сервиса
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.StatusType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Тип статуса сервиса
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.StatusType type = 1;</code>
   * @return The type.
   */
  com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.StatusType getType();

  /**
   * <pre>
   * Детальное описание статуса сервиса
   * </pre>
   *
   * <code>optional string details = 2;</code>
   * @return Whether the details field is set.
   */
  boolean hasDetails();
  /**
   * <pre>
   * Детальное описание статуса сервиса
   * </pre>
   *
   * <code>optional string details = 2;</code>
   * @return The details.
   */
  java.lang.String getDetails();
  /**
   * <pre>
   * Детальное описание статуса сервиса
   * </pre>
   *
   * <code>optional string details = 2;</code>
   * @return The bytes for details.
   */
  com.google.protobuf.ByteString
      getDetailsBytes();

  /**
   * <pre>
   * Время следующей отправки статуса
   * </pre>
   *
   * <code>optional int64 nextTime = 3;</code>
   * @return Whether the nextTime field is set.
   */
  boolean hasNextTime();
  /**
   * <pre>
   * Время следующей отправки статуса
   * </pre>
   *
   * <code>optional int64 nextTime = 3;</code>
   * @return The nextTime.
   */
  long getNextTime();

  /**
   * <pre>
   * Расширенная информация статуса
   * </pre>
   *
   * <code>optional .com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus = 4;</code>
   * @return Whether the advStatus field is set.
   */
  boolean hasAdvStatus();
  /**
   * <pre>
   * Расширенная информация статуса
   * </pre>
   *
   * <code>optional .com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus = 4;</code>
   * @return The advStatus.
   */
  com.racerssquad.besthack2023.DTO.proto.AdvInfo getAdvStatus();
  /**
   * <pre>
   * Расширенная информация статуса
   * </pre>
   *
   * <code>optional .com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus = 4;</code>
   */
  com.racerssquad.besthack2023.DTO.proto.AdvInfoOrBuilder getAdvStatusOrBuilder();
}
